#!/usr/bin/env bash

target=$(( $RANDOM % 100 ))

guess=-1

until [[ $guess = $target ]]; do
  read -p 'Enter your guess for random number: ' guess

  if [[ $guess -gt $target ]]; then
    echo 'Smaller!'
  elif [[ $guess -lt $target ]]; then
    echo 'Higher!'
  else
    echo 'correct' $target 'is yours'
  fi
done

exit 0;
